font:
  size: 14
  normal:
    family: Fira Code
    style: Regular
  offset:
    x: 0
    y: 10

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: On

live_config_reload: true

shell:
  program: /usr/bin/zsh

mouse:
  hide_when_typing: true

window:
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 2
    y: 2
  dynamic_title: true
  gtk_theme_variant: dark

scrolling:
  history: 10000

colors:
  primary:
    background:        &gruvbox_dark_bg '#282828'
    foreground:        '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text:   CellBackground
    cursor: CellForeground
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   *gruvbox_dark_bg
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'
